# Generated by Django 4.2.3 on 2023-07-08 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('trainer_id', models.AutoField(primary_key=True, serialize=False)),
                ('trainer_name', models.CharField(max_length=100, verbose_name='Trainer Name')),
                ('trainer_email', models.CharField(max_length=100, verbose_name='Trainer Email')),
                ('trainer_phone', models.CharField(max_length=100, verbose_name='Trainer Phone')),
                ('trainer_address', models.CharField(max_length=100, verbose_name='Trainer Address')),
                ('dob', models.DateField(default='dd/mm/yyyy')),
                ('start_work', models.DateField(auto_now_add=True)),
                ('photo', models.FileField(blank=True, upload_to='photos/')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                              to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
