# Generated by Django 3.1.2 on 2023-07-03 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ['equipment_name']},
        ),
    ]
