# Generated by Django 4.2.3 on 2023-07-03 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_auto_20230703_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='equipment_status',
            field=models.CharField(choices=[('available', 'Available'), ('in use', 'In Use'), ('maintenance', 'Maintenance'), ('repair', 'Repair'), ('out of order', 'Out of Order')], max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
