# Generated by Django 4.2.3 on 2023-07-11 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_alter_equipment_equipment_status_alter_equipment_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='room',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=50)),
                ('room_location', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='equipment_quantity',
        ),
        migrations.AddField(
            model_name='equipment',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='equipment.room'),
        ),
    ]
