# Generated by Django 4.2.3 on 2023-07-03 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_auto_20230703_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatereports',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
