# Generated by Django 4.2.3 on 2023-07-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('member_name', models.CharField(max_length=50, verbose_name='Member Name')),
                ('review_content', models.CharField(max_length=300, verbose_name='Review Content')),
                ('review_date', models.DateField(auto_now_add=True)),
                ('review_star', models.IntegerField(verbose_name='Review Star')),
            ],
        ),
    ]
