# Generated by Django 4.2.3 on 2023-07-08 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0038_rename_id_member_member_id'),
        ('review', '0003_rename_member_review_member_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='member_id',
        ),
        migrations.AddField(
            model_name='review',
            name='member',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='members.member'),
        ),
    ]
