# Generated by Django 4.2.3 on 2023-07-19 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0048_alter_member_amount_alter_member_subscription_type'),
        ('review', '0004_remove_review_member_id_review_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='member',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.member'),
        ),
    ]
