# Generated by Django 4.2.3 on 2023-07-05 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0030_member_user_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='user',
        ),
    ]
