# Generated by Django 4.2.3 on 2023-07-08 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('trainers', '0001_initial'),
        ('members', '0033_alter_member_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='trainer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='trainers.trainer'),
        ),
    ]
