# Generated by Django 4.2.3 on 2023-07-11 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0038_rename_id_member_member_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='subscription_type',
        ),
    ]
