# Generated by Django 4.2.3 on 2023-07-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0039_remove_member_subscription_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='subscription_type',
            field=models.CharField(choices=[('gym', 'Gym'), ('cross_fit', 'Cross Fit'), ('gym_and_cross_fit', 'Gym + Cross Fit'), ('pt', 'Personal Training')], default='gym', max_length=30, verbose_name='Subscription Type'),
        ),
    ]
