# Generated by Django 4.2.3 on 2023-07-11 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipment', '0004_room_remove_equipment_equipment_quantity_and_more'),
        ('members', '0040_member_subscription_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='room',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='equipment.room'),
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('manager_id', models.AutoField(primary_key=True, serialize=False)),
                ('manager_name', models.CharField(max_length=100, verbose_name='Manager Name')),
                ('manager_email', models.CharField(max_length=100, verbose_name='Manager Email')),
                ('manager_phone', models.CharField(max_length=100, verbose_name='Manager Phone')),
                ('manager_address', models.CharField(max_length=100, verbose_name='Manager Address')),
                ('dob', models.DateField(default='dd/mm/yyyy')),
                ('start_work', models.DateField(auto_now_add=True)),
                ('photo', models.FileField(blank=True, upload_to='photos/')),
                ('room', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='equipment.room')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
