# Generated by Django 4.2.3 on 2023-07-19 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0042_training_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='trainer',
        ),
    ]
