# Generated by Django 4.2.3 on 2023-07-19 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0043_remove_member_trainer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('subscription_id', models.AutoField(primary_key=True, serialize=False)),
                ('subscription_type', models.CharField(max_length=50, verbose_name='Subscription Type')),
            ],
        ),
    ]
