# Generated by Django 4.2.3 on 2023-07-19 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0044_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='status',
            field=models.IntegerField(choices=[(0, 'Start'), (1, 'Stop')], default=0),
        ),
        migrations.AlterField(
            model_name='member',
            name='subscription_type',
            field=models.CharField(choices=[('gym', 'gym'), ('cross_fit', 'cross_fit'), ('gym_and_cross_fit', 'gym_and_cross_fit'), ('Personal Training', 'Personal Training')], default='gym', max_length=30, verbose_name='Subscription Type'),
        ),
    ]
