# Generated by Django 4.2.3 on 2023-07-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0044_remove_subscription_id_subscription_price_per_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='subscription_type_id',
        ),
        migrations.AddField(
            model_name='subscription',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
