# Generated by Django 4.2.3 on 2023-07-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0045_remove_subscription_subscription_type_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='subscription_type',
            field=models.CharField(choices=[('gym', 'Gym'), ('cross_fit', 'Cross Fit'), ('gym_and_cross_fit', 'Gym + Cross Fit'), ('pt', 'Personal Training')], default='gym', max_length=30, verbose_name='Subscription Type'),
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
