# Generated by Django 4.2.3 on 2023-07-19 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0045_subscription_status_alter_member_subscription_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='price_per_month',
            field=models.IntegerField(default=0, verbose_name='Price Per Month'),
        ),
        migrations.AlterField(
            model_name='member',
            name='subscription_type',
            field=models.CharField(choices=[('Gym', 'Gym'), ('Cross Fit', 'Cross Fit'), ('Gym + Cross Fit', 'Gym + Cross Fit'), ('Personal Training', 'Personal Training')], default='gym', max_length=30, verbose_name='Subscription Type'),
        ),
    ]
