# Generated by Django 4.2.3 on 2023-07-19 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0046_subscription_price_per_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='price_per_year',
            field=models.IntegerField(default=0, verbose_name='Price Per Year'),
        ),
        migrations.AlterField(
            model_name='member',
            name='subscription_period',
            field=models.CharField(choices=[('1', '1 Month'), ('2', '2 Months'), ('3', '3 Months'), ('4', '4 Months'), ('5', '5 Months'), ('6', '6 Months'), ('7', '7 Months'), ('8', '8 Months'), ('9', '9 Months'), ('10', '10 Months'), ('11', '11 Months'), ('12', '12 Months'), ('24', '24 Months')], default='1', max_length=30, verbose_name='Subscription Period'),
        ),
    ]
