# Generated by Django 4.2.3 on 2023-07-19 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0003_trainer_user'),
        ('members', '0048_alter_member_amount_alter_member_subscription_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='subscription_type',
            field=models.CharField(choices=[('Gym', 'Gym'), ('Cross Fit', 'Cross Fit'), ('Gym + Cross Fit', 'Gym + Cross Fit'), ('Personal Training', 'Personal Training'), ('Cross Fit + Gym + Personal Training', 'Cross Fit + Gym + Personal Training'), ('Test gói tập', 'Test gói tập')], default='gym', max_length=100, verbose_name='Subscription Type'),
        ),
        migrations.AlterField(
            model_name='training_history',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trainers.trainer'),
        ),
    ]
