# Generated by Django 4.2.3 on 2023-07-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0049_alter_member_subscription_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training_history',
            name='training_date',
            field=models.DateField(default='dd/mm/yyyy'),
        ),
    ]
